// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./array.test.js')
  await import('./boolean.test.js')
  await import('./date.test.js')
  await import('./either.test.js')
  await import('./fn.test.js')
  await import('./identity.test.js')
  await import('./lens.test.js')
  await import('./logic.test.js')
  await import('./map.test.js')
  await import('./maybe.test.js')
  await import('./nil.test.js')
  await import('./nonempty.test.js')
  await import('./number.test.js')
  await import('./ordering.test.js')
  await import('./pair.test.js')
  await import('./regexp.test.js')
  await import('./set.test.js')
  await import('./state-either.test.js')
  await import('./state.test.js')
  await import('./string.test.js')
  await import('./strmap.test.js')
  await import('./these.test.js')
  await import('./validation.test.js')

  test.resume()
}
